[input_parameters]
Lx = 50.0
Ly = 50.0
Lz = 1.0
mi_me = 25.0
Ti_Te = 1.0
qs = [-1.0, 1.0]
alpha_s = [0.25, 0.25, 0.25, 0.05, 0.05, 0.05]
u_s = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Omega_cs = [0.5, 0.02]
nu = 1.0
D = 0.0
t_max = 1000.0
ode_tolerance = 1e-7

[solver_parameters]
Nx = 151
Ny = 151
Nz = 1
Nn = 6
Nm = 6
Np = 6
Ns = 2
timesteps = 3
dt = 0.0001
solver = "Dopri8"